#!/usr/bin/env bash
# Write infra/compose.env for Docker Compose project interpolation only.
# Secrets stay in .env and are passed to api/worker via env_file (literal).
# Using a narrow env file avoids Compose expanding "$" inside COOKIE_ENCRYPTION_SEED
# / SECRET_KEY (warnings like: The "G" variable is not set).
#
# Usage: write-compose-env.sh [app-dir]
set -euo pipefail

APP_DIR="${1:-.}"
cd "$APP_DIR"

_env_val() {
  grep -E "^${1}=" .env 2>/dev/null | head -1 | cut -d= -f2- || true
}

DOMAIN="${DOMAIN:-$(_env_val DOMAIN)}"
ACME_EMAIL="${ACME_EMAIL:-$(_env_val ACME_EMAIL)}"
# Caller IMAGE_TAG wins; else .env; else latest.
if [[ -z "${IMAGE_TAG:-}" ]]; then
  IMAGE_TAG="$(_env_val IMAGE_TAG)"
fi
IMAGE_TAG="${IMAGE_TAG:-latest}"

OUT="infra/compose.env"
mkdir -p infra
cat > "$OUT" <<EOF
# Auto-generated — docker compose --env-file (not secrets).
# Regenerated by fix-gcloud-vm.sh / vm-startup.sh.
IMAGE_TAG=${IMAGE_TAG}
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}
EOF

echo "Wrote $OUT (IMAGE_TAG=${IMAGE_TAG} DOMAIN=${DOMAIN:-none})"
